import { useEffect, useState } from 'react';
import { Alert, ActivityIndicator, Image, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View, useWindowDimensions } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import * as FileSystem from 'expo-file-system';
import * as MediaLibrary from 'expo-media-library';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { generateImage, GenerationSettings } from '../src/novelai';
import { api, getSession, Session } from '../src/backend';

type Tab = 'Генерация' | 'История' | 'Telegram' | 'Настройки';
const defaults: GenerationSettings = { prompt: '', negativePrompt: '', width: 832, height: 1216, steps: 28, seed: -1, spendAnlas: false };
export default function App() {
 const [session,setSession]=useState<Session|null>(null); const [tab,setTab]=useState<Tab>('Генерация'); const [settings,setSettings]=useState(defaults); const [token,setToken]=useState(''); const [loading,setLoading]=useState(false); const [history,setHistory]=useState<any[]>([]); const [tg,setTg]=useState<any>(null); const {width}=useWindowDimensions(); const wide=width>700;
 useEffect(()=>{ getSession().then(setSession); SecureStore.getItemAsync('nai_persistent_token').then(x=>setToken(x||'')); AsyncStorage.getItem('history').then(x=>x&&setHistory(JSON.parse(x))); },[]);
 useEffect(()=>{ if(session) api('/tg/status').then(setTg).catch(()=>{}); },[session]);
 if(!session) return <Auth onDone={setSession}/>;
 const saveToken=async()=>{ if(!token.startsWith('pst-')) return Alert.alert('Неверный токен','Токен NovelAI должен начинаться с pst-.'); await SecureStore.setItemAsync('nai_persistent_token',token); Alert.alert('Сохранено','Токен хранится только в защищённом хранилище устройства.'); };
 const run=async()=>{ if(!token.startsWith('pst-')) return setTab('Настройки'); setLoading(true); try { const out=await generateImage(token,settings); const size=`${settings.width}×${settings.height}`; const folder=`${FileSystem.documentDirectory}history/`; await FileSystem.makeDirectoryAsync(folder,{intermediates:true}); const uri=`${folder}${Date.now()}-${out.seed}.${out.extension}`; await FileSystem.writeAsStringAsync(uri,out.base64,{encoding:FileSystem.EncodingType.Base64}); const item={uri,prompt:settings.prompt,seed:out.seed,model:out.model,createdAt:Date.now(),size}; const next=[item,...history].slice(0,30); setHistory(next); await AsyncStorage.setItem('history',JSON.stringify(next)); const permission=await MediaLibrary.requestPermissionsAsync(); if(permission.granted) await MediaLibrary.createAssetAsync(uri); api('/tg/mirror',{method:'POST',body:JSON.stringify({imageBase64:out.base64,prompt:settings.prompt,seed:out.seed,model:out.model,size})}).catch(()=>{}); Alert.alert('Готово',permission.granted?'Изображение сохранено в истории, галерее и отправлено в Telegram при привязке.':'Изображение сохранено в истории. Доступ к галерее не выдан.'); } catch(e:any){ Alert.alert('Ошибка генерации',e.message||'Неизвестная ошибка'); } finally {setLoading(false)} };
 return <View style={s.app}><View style={[s.nav,wide&&s.navWide]}><Text style={s.logo}>NAI Opus</Text>{(['Генерация','История','Telegram','Настройки'] as Tab[]).map(x=><Pressable key={x} style={[s.navButton,tab===x&&s.active]} onPress={()=>setTab(x)}><Text style={s.navText}>{x}</Text></Pressable>)}</View><ScrollView contentContainerStyle={[s.content,wide&&s.contentWide]}>
 {tab==='Генерация'&&<Generate settings={settings} setSettings={setSettings} run={run} loading={loading}/>} {tab==='История'&&<History data={history}/>} {tab==='Telegram'&&<Telegram tg={tg} refresh={()=>api('/tg/status').then(setTg)} />} {tab==='Настройки'&&<Settings token={token} setToken={setToken} save={saveToken} settings={settings} setSettings={setSettings}/>}</ScrollView></View>;
}
function Auth({onDone}:{onDone:(s:Session)=>void}){const [login,setLogin]=useState(true),[id,setId]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{onDone(await api(login?'/auth/login':'/auth/register',{method:'POST',body:JSON.stringify({identifier:id,password})}))}catch(e:any){Alert.alert('Не удалось войти',e.message)}finally{setBusy(false)}};return <View style={s.auth}><Text style={s.title}>NAI Opus</Text><Text style={s.muted}>Лёгкая учётная запись для привязки Telegram.</Text><TextInput placeholder="Никнейм или email" placeholderTextColor="#888" style={s.input} value={id} onChangeText={setId}/><TextInput secureTextEntry placeholder="Пароль (минимум 8)" placeholderTextColor="#888" style={s.input} value={password} onChangeText={setPassword}/><Pressable style={s.primary} onPress={submit}><Text style={s.buttonText}>{busy?'…':login?'Войти':'Зарегистрироваться'}</Text></Pressable><Pressable onPress={()=>setLogin(!login)}><Text style={s.link}>{login?'Создать аккаунт':'У меня уже есть аккаунт'}</Text></Pressable></View>}
function Generate(p:any){const set=(k:keyof GenerationSettings,v:any)=>p.setSettings({...p.settings,[k]:v});const paid=p.settings.spendAnlas;return <View><Text style={s.title}>Генерация</Text><Text style={s.muted}>Opus: nai-diffusion-4-5-full · Normal · 1 изображение</Text><TextInput multiline placeholder="Промпт" placeholderTextColor="#888" style={[s.input,s.area]} value={p.settings.prompt} onChangeText={v=>set('prompt',v)}/><TextInput multiline placeholder="Негативный промпт" placeholderTextColor="#888" style={[s.input,s.area]} value={p.settings.negativePrompt} onChangeText={v=>set('negativePrompt',v)}/><TextInput multiline placeholder="Необязательный промпт персонажа" placeholderTextColor="#888" style={[s.input,s.area]} value={p.settings.characterPrompt} onChangeText={v=>set('characterPrompt',v)}/><View style={s.row}><Field label={paid?'Шаги (≤50)':'Шаги (≤28)'} value={String(p.settings.steps)} onChange={v=>set('steps',Number(v)||28)}/><Field label="Seed (-1 случайный)" value={String(p.settings.seed)} onChange={v=>set('seed',Number(v)||-1)}/></View>{paid&&<View style={s.row}><Field label="Ширина (Normal)" value={String(p.settings.width)} onChange={v=>set('width',Number(v)||832)}/><Field label="Высота (Normal)" value={String(p.settings.height)} onChange={v=>set('height',Number(v)||1216)}/></View>}<View style={s.warning}><Text style={s.warningText}>{paid?'Anlas включён: доступны другие Normal-размеры и до 50 шагов.':'Расход Anlas выключен. Только 832×1216 и до 28 шагов.'}</Text></View><Pressable style={s.primary} onPress={p.run} disabled={p.loading}><Text style={s.buttonText}>{p.loading?<ActivityIndicator color="#fff"/>:'Сгенерировать'}</Text></Pressable></View>}
function Field({label,value,onChange}:any){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput keyboardType="numeric" style={s.input} value={value} onChangeText={onChange}/></View>};
function History({data}:any){return <View><Text style={s.title}>История</Text>{data.length===0?<Text style={s.muted}>Пока нет генераций.</Text>:data.map((x:any,i:number)=><View key={i} style={s.card}>{x.uri&&<Image accessibilityLabel="Сгенерированное изображение" source={{uri:x.uri}} style={s.image}/>}<Text numberOfLines={2}>{x.prompt||'Без промпта'}</Text><Text style={s.muted}>{x.size} · seed {x.seed}</Text></View>)}</View>}
function Telegram({tg,refresh}:any){const [link,setLink]=useState<{code:string;deepLink:string}|null>(null);const start=async()=>{try{const r=await api('/tg/link/start',{method:'POST'});setLink({code:r.linkCode,deepLink:r.deepLink});refresh()}catch(e:any){Alert.alert('Ошибка',e.message)}};return <View><Text style={s.title}>Telegram</Text><Text style={s.muted}>{tg?.linked?'✅ Telegram привязан':'Не привязан'}</Text><Pressable style={s.primary} onPress={start}><Text style={s.buttonText}>Получить код привязки</Text></Pressable>{link&&<View style={s.card}><Text>Откройте бота и подтвердите привязку:</Text><Pressable onPress={()=>Linking.openURL(link.deepLink)}><Text style={s.link}>Открыть Telegram-бота</Text></Pressable><Text style={s.muted}>Если ссылка не открылась, отправьте: </Text><Text style={s.code}>/start {link.code}</Text></View>}</View>}
function Settings(p:any){return <View><Text style={s.title}>Настройки</Text><Text style={s.label}>Persistent API Token NovelAI</Text><TextInput autoCapitalize="none" autoCorrect={false} secureTextEntry style={s.input} placeholder="pst-…" placeholderTextColor="#888" value={p.token} onChangeText={p.setToken}/><Pressable style={s.primary} onPress={p.save}><Text style={s.buttonText}>Сохранить токен</Text></Pressable><View style={s.card}><View style={s.row}><Text>Расходовать Anlas</Text><Switch value={p.settings.spendAnlas} onValueChange={(v)=>p.setSettings({...p.settings,spendAnlas:v})}/></View><Text style={s.warningText}>По умолчанию выключено. При включении доступны Normal-размеры и до 50 шагов.</Text></View></View>}
const s=StyleSheet.create({app:{flex:1,backgroundColor:'#101116',flexDirection:'row'},nav:{backgroundColor:'#171922',padding:16,gap:8},navWide:{width:190,paddingTop:55},logo:{color:'#cdb9ff',fontSize:22,fontWeight:'700',marginBottom:15},navButton:{padding:10,borderRadius:8},active:{backgroundColor:'#493783'},navText:{color:'#fff'},content:{padding:20,flexGrow:1,maxWidth:860,width:'100%'},contentWide:{padding:40},auth:{flex:1,justifyContent:'center',padding:28,backgroundColor:'#101116'},title:{fontSize:29,color:'#fff',fontWeight:'700',marginBottom:8},muted:{color:'#a5a8b5',marginBottom:16},input:{backgroundColor:'#242631',borderRadius:9,color:'#fff',padding:13,marginVertical:7,fontSize:16},area:{minHeight:94,textAlignVertical:'top'},primary:{backgroundColor:'#7658d6',padding:14,borderRadius:9,alignItems:'center',marginVertical:10},buttonText:{color:'#fff',fontSize:16,fontWeight:'700'},link:{color:'#bfaaff',textAlign:'center',padding:10},row:{flexDirection:'row',gap:12,alignItems:'center',justifyContent:'space-between'},field:{flex:1},label:{color:'#d5d7df',marginTop:10},warning:{backgroundColor:'#3a2d18',padding:12,borderRadius:8,marginTop:15},warningText:{color:'#f0cb77',lineHeight:20},card:{backgroundColor:'#1d1f29',padding:15,borderRadius:10,marginTop:14},image:{width:'100%',height:310,borderRadius:7,resizeMode:'contain',backgroundColor:'#111',marginBottom:10},code:{color:'#cdb9ff',fontFamily:'monospace',fontSize:17,marginVertical:10}});
