import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import { existsSync, readFileSync, writeFileSync } from 'node:fs'; import { randomBytes } from 'node:crypto';
type User={id:string;identifier:string;passwordHash:string;chatId?:string;linkCode?:string}; type Store={users:User[]};
const dataFile=process.env.DATA_FILE||'data.json'; const load=():Store=>existsSync(dataFile)?JSON.parse(readFileSync(dataFile,'utf8')):{users:[]}; const save=(d:Store)=>writeFileSync(dataFile,JSON.stringify(d,null,2)); const secret=process.env.JWT_SECRET||'development-only-change-me';
const app=express(); app.use(cors()); app.use(express.json({limit:'12mb'}));
function auth(req:express.Request,res:express.Response,next:express.NextFunction){try{const raw=req.headers.authorization?.replace('Bearer ','');const claims=jwt.verify(raw||'',secret) as {sub:string};const user=load().users.find(x=>x.id===claims.sub);if(!user)throw Error();(req as any).user=user;next()}catch{res.status(401).json({error:'Требуется вход.'})}}
function issue(user:User){return {token:jwt.sign({sub:user.id},secret,{expiresIn:'30d'}),user:{id:user.id,identifier:user.identifier}}}
app.post('/auth/register',async(req,res)=>{const identifier=String(req.body.identifier||'').trim();const password=String(req.body.password||'');if(identifier.length<3||password.length<8)return res.status(400).json({error:'Никнейм — от 3 символов, пароль — от 8.'});const db=load();if(db.users.some(x=>x.identifier.toLowerCase()===identifier.toLowerCase()))return res.status(409).json({error:'Этот пользователь уже существует.'});const user:User={id:randomBytes(12).toString('hex'),identifier,passwordHash:await bcrypt.hash(password,12)};db.users.push(user);save(db);res.json(issue(user))});
app.post('/auth/login',async(req,res)=>{const user=load().users.find(x=>x.identifier.toLowerCase()===String(req.body.identifier||'').trim().toLowerCase());if(!user||!await bcrypt.compare(String(req.body.password||''),user.passwordHash))return res.status(401).json({error:'Неверный логин или пароль.'});res.json(issue(user))});
app.post('/tg/link/start',auth,(req,res)=>{const db=load();const user=db.users.find(x=>x.id===(req as any).user.id)!;user.linkCode=randomBytes(5).toString('hex');save(db);res.json({linkCode:user.linkCode})});
app.get('/tg/status',auth,(req,res)=>res.json({linked:Boolean((req as any).user.chatId)}));
app.post('/tg/mirror',auth,async(req,res)=>{const user=(req as any).user as User;if(!user.chatId)return res.json({mirrored:false,reason:'not_linked'});const bot=process.env.TELEGRAM_BOT_TOKEN;if(!bot)return res.status(503).json({error:'Telegram bot не настроен.'});const {imageBase64,prompt='',seed,model,size}=req.body;if(typeof imageBase64!=='string')return res.status(400).json({error:'Нет изображения.'});const caption=`${String(prompt).slice(0,600)||'Без промпта'}\nseed: ${seed} · ${model} · ${size}`;const form=new FormData();form.set('chat_id',user.chatId);form.set('caption',caption);form.set('photo',new Blob([Buffer.from(imageBase64,'base64')],{type:'image/png'}),'generation.png');const r=await fetch(`https://api.telegram.org/bot${bot}/sendPhoto`,{method:'POST',body:form});if(!r.ok)return res.status(502).json({error:'Telegram не принял изображение.'});res.json({mirrored:true})});
async function poll(){const bot=process.env.TELEGRAM_BOT_TOKEN;if(!bot)return;let offset=0;for(;;){try{const r=await fetch(`https://api.telegram.org/bot${bot}/getUpdates?timeout=25&offset=${offset}`);const d:any=await r.json();for(const u of d.result||[]){offset=u.update_id+1;const text=u.message?.text||'';const match=text.match(/^\/start\s+([a-f0-9]+)$/i);if(match){const db=load(),user=db.users.find(x=>x.linkCode===match[1]);if(user){user.chatId=String(u.message.chat.id);user.linkCode=undefined;save(db);await fetch(`https://api.telegram.org/bot${bot}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:user.chatId,text:'✅ Telegram привязан. Новые генерации будут приходить сюда.'})})}}}}catch(e){console.error('Telegram polling error',e)} }}
app.listen(Number(process.env.PORT||3000),()=>console.log('Server listening')); poll();
